tags:
  name: "task"
  description: "Everything about Tasks"
paths:
  /task:
    post:
      tags:
      - "task"
      summary: "Add a new task"
      description: ""
      operationId: "addTask"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Task object that needs to be added"
        required: true
        schema:
          $ref: "#/definitions/Task"
      responses:
        405:
          description: "Invalid input"
      security:
      x-swagger-router-controller: "Task"
    get:
      tags:
      - "task"
      summary: "Get task list"
      description: ""
      operationId: "getTaskList"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "object"
            items:
              total: "number"
              items:
                type: "array"
                items:
                  type: "object"
      security:
      x-swagger-router-controller: "Task"
  /pet/{petId}:
    get:
      tags:
      - "task"
      summary: "Find task by ID"
      description: "Returns a single task"
      operationId: "getTaskById"
      produces:
      - "application/json"
      parameters:
      - name: "taskId"
        in: "path"
        description: "ID of task to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Task"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Task not found"
      security:
      x-swagger-router-controller: "Task"
    post:
      tags:
      - "task"
      summary: "Updates a task with form data"
      description: ""
      operationId: "updateTask"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/json"
      - "application/xml"
      parameters:
      - name: "taskId"
        in: "path"
        description: "ID of task that needs to be updated"
        required: true
        type: "integer"
        format: "int64"
      - name: "body"
        in: "body"
        description: "Task object that needs to be updated"
        required: true
        schema:
          $ref: "#/definitions/Task"
      responses:
        200:
          description: "successful operation"
        405:
          description: "Invalid input"
      security:
      x-swagger-router-controller: "Task"
    delete:
      tags:
      - "task"
      summary: "Deletes a task"
      description: ""
      operationId: "deleteTask"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "taskId"
        in: "path"
        description: "Task id to delete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        400:
          description: "Invalid ID supplied"
        404:
          description: "Task not found"
      security:
      x-swagger-router-controller: "Task"
definitions:
  Task:
    type: "object"
    required:
    - "name"
    - "isComp"
    properties:
      id:
        type: "integer"
        format: "int64"
      isCompleted:
        type: "boolean"
        default: "false"
      title:
        type: "string"
        example: "title"
      content:
        type: "string"
        example: "content"
      deadline:
        type: "integer"
        format: "int64"